@extends('layouts.app')

@section('title', auth()->user()->hasBackOfficeAccess() ? 'All Contracts' : 'My Contracts')
@section('subtitle', 'Student service agreements')

@section('content')
    <div class="panel">
        <div class="panel-head">
            <div><h2>Contracts</h2><p>&nbsp;</p></div>
            <a href="{{ route('contracts.create') }}" class="btn btn-primary btn-sm">+ Generate Contract</a>
        </div>

        <div class="table-responsive">
            <table class="table table-hover mb-0">
                <thead>
                    <tr>
                        <th>Student</th>
                        <th>University</th>
                        <th>Country</th>
                        <th>Total Fee</th>
                        <th>Date</th>
                        @if (auth()->user()->hasBackOfficeAccess())
                            <th>Generated by</th>
                        @endif
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($contracts as $contract)
                        <tr>
                            <td>{{ $contract->student->name }}</td>
                            <td>{{ $contract->university_tbd ? 'TBD' : ($contract->university ?: '—') }}</td>
                            <td>{{ $contract->country ?: '—' }}</td>
                            <td>{{ $contract->total_fee ? number_format($contract->total_fee, 2).' '.$contract->currency : '—' }}</td>
                            <td>{{ $contract->created_at->format('M j, Y') }}</td>
                            @if (auth()->user()->hasBackOfficeAccess())
                                <td>{{ $contract->creator->name }}</td>
                            @endif
                            <td><a href="{{ route('contracts.show', $contract) }}" class="btn btn-sm btn-outline-primary">View</a></td>
                        </tr>
                    @empty
                        <tr><td colspan="7" class="empty-state">No contracts generated yet.</td></tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
@endsection
