<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
</head>
<body style="margin:0;padding:0;background:#F5F5F0;font-family:Arial,Helvetica,sans-serif;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#F5F5F0;padding:24px 0;">
        <tr>
            <td align="center">
                <table role="presentation" width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:6px;overflow:hidden;">
                    <tr>
                        <td style="background:#1F4E86;padding:18px 24px;">
                            <span style="color:#ffffff;font-size:16px;font-weight:bold;">THE GUIDERS</span>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding:24px;color:#1B1F22;font-size:14px;line-height:1.6;">
                            @if ($forClient)
                                <p>Dear {{ $contract->student->name }},</p>
                                <p>Your Student Service Agreement with The Guiders has been generated. A summary is below — our team will share the full signed copy separately.</p>
                            @else
                                <p>A new contract was generated for <strong>{{ $contract->student->name }}</strong>.</p>
                            @endif

                            <table role="presentation" width="100%" cellpadding="4" cellspacing="0" style="font-size:13px;margin:16px 0;border-collapse:collapse;">
                                <tr><td style="color:#5B6570;width:160px;">Service type</td><td><strong>{{ $contract->service_type ?: '—' }}</strong></td></tr>
                                <tr><td style="color:#5B6570;">Destination</td><td><strong>{{ $contract->university_tbd ? 'To be finalized' : ($contract->university ?: '—') }}{{ $contract->country ? ', '.$contract->country : '' }}</strong></td></tr>
                                <tr><td style="color:#5B6570;">Intake</td><td><strong>{{ $contract->intake ?: '—' }}</strong></td></tr>
                                <tr><td style="color:#5B6570;">Total fee</td><td><strong>{{ $contract->total_fee ? number_format($contract->total_fee, 2).' '.$contract->currency : '—' }}</strong></td></tr>
                                <tr><td style="color:#5B6570;">Agreement date</td><td><strong>{{ $contract->created_at->format('M j, Y') }}</strong></td></tr>
                            </table>

                            @if ($forClient)
                                <p>If you have any questions about this agreement, please reach out to your counselor.</p>
                            @else
                                <p>Generated by {{ $contract->creator->name }}.</p>
                            @endif
                        </td>
                    </tr>
                    <tr>
                        <td style="padding:0 24px 24px;color:#5B6570;font-size:12px;">
                            The Guiders Overseas Educational Services
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>
