@extends('layouts.app')

@section('title', auth()->user()->hasBackOfficeAccess() ? 'All Invoices' : 'My Invoices')
@section('subtitle', 'Generated invoice records')

@section('content')
    <div class="panel">
        <div class="panel-head">
            <div><h2>Invoices</h2><p>&nbsp;</p></div>
            <a href="{{ route('invoices.create') }}" class="btn btn-primary btn-sm">+ Generate Invoice</a>
        </div>

        <div class="table-responsive">
            <table class="table table-hover mb-0">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Student</th>
                        <th>Issued</th>
                        <th>Due</th>
                        <th>Total</th>
                        @if (auth()->user()->hasBackOfficeAccess())
                            <th>Generated by</th>
                        @endif
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($invoices as $invoice)
                        <tr>
                            <td>{{ $invoice->invoice_number }}</td>
                            <td>{{ $invoice->student->name }}</td>
                            <td>{{ $invoice->issued_date->format('M j, Y') }}</td>
                            <td>{{ $invoice->due_date?->format('M j, Y') ?? '—' }}</td>
                            <td>{{ $invoice->currency }} {{ number_format($invoice->total, 2) }}</td>
                            @if (auth()->user()->hasBackOfficeAccess())
                                <td>{{ $invoice->creator->name }}</td>
                            @endif
                            <td><a href="{{ route('invoices.show', $invoice) }}" class="btn btn-sm btn-outline-primary">View</a></td>
                        </tr>
                    @empty
                        <tr><td colspan="7" class="empty-state">No invoices generated yet.</td></tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
@endsection
