@extends('layouts.app')

@section('title', 'Invoice '.$invoice->invoice_number)
@section('subtitle', $invoice->student->name)

@section('content')
    <div class="panel print-area">
        <div class="panel-head no-print">
            <div><h2>Invoice {{ $invoice->invoice_number }}</h2><p>&nbsp;</p></div>
            <button type="button" class="btn btn-outline-secondary btn-sm" onclick="window.print()">Print</button>
        </div>

        <div class="invoice-sheet p-4">
            <div class="d-flex justify-content-between align-items-start mb-4">
                <div class="d-flex align-items-center gap-2">
                    <img src="{{ asset('img/logo/logoguidr.png') }}" alt="{{ $company->company_name ?? 'The Guiders' }}" style="height:64px">
                    <div>
                        <div class="fw-bold">{{ $company->company_name ?? 'THE GUIDERS' }}</div>
                    </div>
                </div>
                <div class="text-end">
                    <h1 class="mb-0" style="letter-spacing:2px;">INVOICE</h1>
                    <div class="text-muted"># {{ $invoice->invoice_number }}</div>
                </div>
            </div>

            <div class="d-flex justify-content-between mb-4">
                <div>
                    <div class="text-muted small">Bill To:</div>
                    <div class="fw-bold">{{ strtoupper($invoice->student->name) }}</div>
                </div>
                <div class="text-end">
                    <div><span class="text-muted small">Date:</span> {{ $invoice->issued_date->format('M j, Y') }}</div>
                    @if ($invoice->due_date)
                        <div><span class="text-muted small">Due Date:</span> {{ $invoice->due_date->format('M j, Y') }}</div>
                    @endif
                    <div class="mt-2 p-2" style="background:#F0FBF7;">
                        <span class="text-muted small">Balance Due:</span>
                        <strong>{{ $invoice->currency }} {{ number_format($invoice->total, 2) }}</strong>
                    </div>
                </div>
            </div>

            <table class="table mb-4">
                <thead style="background:#2b2b2b;color:#fff;">
                    <tr><th>Item</th><th>{{ $invoice->items->first()->currency ?? 'Currency' }}</th><th>Exchange Rate</th><th class="text-end">Amount</th></tr>
                </thead>
                <tbody>
                    @foreach ($invoice->items as $item)
                        <tr>
                            <td>{{ $item->item }}</td>
                            <td>{{ number_format($item->currency_value, 2) }}</td>
                            <td>{{ number_format($item->exchange_rate, 2) }}</td>
                            <td class="text-end">{{ $invoice->currency }} {{ number_format($item->amount, 2) }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            <div class="d-flex justify-content-end mb-4">
                <div style="min-width:260px;">
                    <div class="d-flex justify-content-between"><span>Subtotal:</span><span>{{ $invoice->currency }} {{ number_format($invoice->subtotal, 2) }}</span></div>
                    <div class="d-flex justify-content-between"><span>Tax:</span><span>{{ $invoice->currency }} {{ number_format($invoice->tax, 2) }}</span></div>
                    <div class="d-flex justify-content-between fw-bold"><span>Total:</span><span>{{ $invoice->currency }} {{ number_format($invoice->total, 2) }}</span></div>
                </div>
            </div>

            @if ($invoice->notes)
                <div class="mb-3">
                    <div class="fw-bold">Notes:</div>
                    <p class="mb-1">{{ $invoice->notes }}</p>
                    @if ($company)
                        <p class="mb-0">
                            Bank name: {{ $company->bank_name }}<br>
                            Account number: {{ $company->account_number }}<br>
                            Branch code: {{ $company->branch_code }}<br>
                            IBAN: {{ $company->iban }}<br>
                            Address: {{ $company->address }}
                        </p>
                    @endif
                </div>
            @endif

            @if ($invoice->terms)
                <div>
                    <div class="fw-bold">Terms:</div>
                    <p class="mb-0">{{ $invoice->terms }}</p>
                </div>
            @endif

            <div class="text-muted small mt-4 no-print">Generated by {{ $invoice->creator->name }}</div>
        </div>
    </div>
@endsection

@push('styles')
<style>
    @media print {
        @page {
            size: A4;
            margin: 12mm;
        }

        .sidebar, .topbar, .no-print { display: none !important; }

        body, .content, .main-content { margin: 0 !important; padding: 0 !important; }

        .panel.print-area {
            border: none !important;
            box-shadow: none !important;
            margin: 0 !important;
        }

        .invoice-sheet {
            padding: 0 !important;
            font-size: 12px;
        }

        .invoice-sheet table { font-size: 12px; }
    }
</style>
@endpush
